"""chunks embeddings fts

Revision ID: 38e380d25b13
Revises: a484086ebc97
Create Date: 2026-09-28 17:31:45.821868
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

revision: str = '38e380d25b13'
down_revision: str | Sequence[str] | None = 'a484086ebc97'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embedding_cache',
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('text_hash', sa.String(length=64), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('model', 'text_hash', name=op.f('pk_embedding_cache'))
    )
    op.create_table('chunks',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=True),
    sa.Column('department_id', sa.Uuid(), nullable=True),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('policy_id', sa.Uuid(), nullable=True),
    sa.Column('version_id', sa.Uuid(), nullable=True),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('section_id', sa.Uuid(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('section_number', sa.String(length=50), nullable=True),
    sa.Column('section_path', sa.Text(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('page_start', sa.Integer(), nullable=False),
    sa.Column('page_end', sa.Integer(), nullable=False),
    sa.Column('char_start', sa.Integer(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('chunk_hash', sa.String(length=64), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('embedding_model', sa.String(length=100), nullable=True),
    sa.Column('tsv', postgresql.TSVECTOR(), sa.Computed("setweight(to_tsvector('english', coalesce(section_path, '')), 'A') || setweight(to_tsvector('english', coalesce(text, '')), 'B')", persisted=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_chunks_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], name=op.f('fk_chunks_policy_id_policies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['document_sections.id'], name=op.f('fk_chunks_section_id_document_sections'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['policy_versions.id'], name=op.f('fk_chunks_version_id_policy_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chunks'))
    )
    op.create_index('ix_chunks_document_index', 'chunks', ['document_id', 'chunk_index'], unique=False)
    op.create_index('ix_chunks_embedding_hnsw', 'chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('ix_chunks_scope', 'chunks', ['organization_id', 'branch_id', 'department_id'], unique=False)
    op.create_index('ix_chunks_section', 'chunks', ['section_id'], unique=False)
    op.create_index('ix_chunks_tsv', 'chunks', ['tsv'], unique=False, postgresql_using='gin')
    op.create_index('ix_chunks_version', 'chunks', ['version_id'], unique=False)
    op.add_column('document_sections', sa.Column('tsv', postgresql.TSVECTOR(), sa.Computed("setweight(to_tsvector('english', coalesce(path, '')), 'A') || setweight(to_tsvector('english', left(coalesce(content, ''), 100000)), 'C')", persisted=True), nullable=True))
    op.create_index('ix_document_sections_tsv', 'document_sections', ['tsv'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_document_sections_tsv', table_name='document_sections', postgresql_using='gin')
    op.drop_column('document_sections', 'tsv')
    op.drop_index('ix_chunks_version', table_name='chunks')
    op.drop_index('ix_chunks_tsv', table_name='chunks', postgresql_using='gin')
    op.drop_index('ix_chunks_section', table_name='chunks')
    op.drop_index('ix_chunks_scope', table_name='chunks')
    op.drop_index('ix_chunks_embedding_hnsw', table_name='chunks', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index('ix_chunks_document_index', table_name='chunks')
    op.drop_table('chunks')
    op.drop_table('embedding_cache')
    # ### end Alembic commands ###
