"""categories documents ingestion stages

Revision ID: 1ea11c5e8448
Revises: 2a70babdd17d
Create Date: 2026-09-28 17:04:10.344611
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '1ea11c5e8448'
down_revision: str | Sequence[str] | None = '2a70babdd17d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('authority_rank', sa.Integer(), nullable=False),
    sa.Column('keywords', postgresql.ARRAY(sa.String(length=100)), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_categories_organization_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('organization_id', 'slug', name='uq_categories_organization_id_slug')
    )
    op.create_index(op.f('ix_categories_organization_id'), 'categories', ['organization_id'], unique=False)
    op.create_table('documents',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=True),
    sa.Column('department_id', sa.Uuid(), nullable=True),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('policy_id', sa.Uuid(), nullable=True),
    sa.Column('policy_version_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('file_sha256', sa.String(length=64), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('simhash', sa.BigInteger(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('ingestion_attempt', sa.Integer(), nullable=False),
    sa.Column('error', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pdf_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('uploaded_by_id', sa.Uuid(), nullable=True),
    sa.Column('duplicate_of_id', sa.Uuid(), nullable=True),
    sa.Column('duplicate_override_reason', sa.Text(), nullable=True),
    sa.Column('ready_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_documents_branch_id_branches'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_documents_category_id_categories'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_documents_department_id_departments'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['duplicate_of_id'], ['documents.id'], name=op.f('fk_documents_duplicate_of_id_documents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_documents_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], name=op.f('fk_documents_uploaded_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    op.create_index('ix_documents_org_category', 'documents', ['organization_id', 'category_id'], unique=False)
    op.create_index('ix_documents_org_content_hash', 'documents', ['organization_id', 'content_hash'], unique=False, postgresql_where=sa.text('content_hash IS NOT NULL'))
    op.create_index('ix_documents_org_file_sha256', 'documents', ['organization_id', 'file_sha256'], unique=False)
    op.create_index('ix_documents_org_status', 'documents', ['organization_id', 'status'], unique=False)
    op.create_index('ix_documents_policy_id', 'documents', ['policy_id'], unique=False)
    op.create_index('ix_documents_scope', 'documents', ['organization_id', 'branch_id', 'department_id'], unique=False)
    op.create_table('ingestion_stages',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('stage', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('done_units', sa.Integer(), nullable=False),
    sa.Column('total_units', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_ingestion_stages_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingestion_stages')),
    sa.UniqueConstraint('document_id', 'stage', name='uq_ingestion_stages_document_id_stage')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ingestion_stages')
    op.drop_index('ix_documents_scope', table_name='documents')
    op.drop_index('ix_documents_policy_id', table_name='documents')
    op.drop_index('ix_documents_org_status', table_name='documents')
    op.drop_index('ix_documents_org_file_sha256', table_name='documents')
    op.drop_index('ix_documents_org_content_hash', table_name='documents', postgresql_where=sa.text('content_hash IS NOT NULL'))
    op.drop_index('ix_documents_org_category', table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_categories_organization_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
