"""document pages and sections

Revision ID: 4449afbc9c74
Revises: 1ea11c5e8448
Create Date: 2026-09-28 17:11:15.975011
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '4449afbc9c74'
down_revision: str | Sequence[str] | None = '1ea11c5e8448'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_pages',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('width', sa.Double(), nullable=True),
    sa.Column('height', sa.Double(), nullable=True),
    sa.Column('lines', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ocr_engine', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_pages_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id', 'page_number', name=op.f('pk_document_pages'))
    )
    op.create_index('ix_document_pages_pending_ocr', 'document_pages', ['document_id'], unique=False, postgresql_where=sa.text("method = 'pending_ocr'"))
    op.create_table('document_sections',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('page_start', sa.Integer(), nullable=False),
    sa.Column('page_end', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('page_marks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_sections_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['document_sections.id'], name=op.f('fk_document_sections_parent_id_document_sections'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_sections'))
    )
    op.create_index('ix_document_sections_document_order', 'document_sections', ['document_id', 'order_index'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_document_sections_document_order', table_name='document_sections')
    op.drop_table('document_sections')
    op.drop_index('ix_document_pages_pending_ocr', table_name='document_pages', postgresql_where=sa.text("method = 'pending_ocr'"))
    op.drop_table('document_pages')
    # ### end Alembic commands ###
